FROM node:18-bullseye AS builder

RUN mkdir -p /usr/src/trudesk
WORKDIR /usr/src/trudesk

COPY . /usr/src/trudesk

RUN apt-get update --fix-missing
RUN apt-get install -y bash make gcc g++ python3
RUN yarn plugin import workspace-tools
RUN yarn workspaces focus --all --production
RUN cp -R node_modules prod_node_modules
RUN yarn install
RUN yarn build
RUN rm -rf node_modules && mv prod_node_modules node_modules
RUN rm -rf .yarn/cache

FROM node:18-bullseye
WORKDIR /usr/src/trudesk
RUN wget https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/5.0/multiverse/binary-arm64/mongodb-org-database-tools-extra_5.0.6_arm64.deb
RUN dpkg -i mongodb-org-database-tools-extra_5.0.6_arm64.deb
RUN apt-get install -y -f
RUN apt-get install -y ca-certificates bash && rm -rf /tmp/*
COPY --from=builder /usr/src/trudesk .

EXPOSE 8118

CMD [ "/bin/bash", "/usr/src/trudesk/startup.sh" ]